services:
  - type: web
    name: ai-ml-project-api
    runtime: python
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.6"
